theme: jekyll-theme-minimal
title: Sudhanshu Pani
description: Dr Sudhanshu Pani is currently a faculty at the School of Business Management, Mumbai. 
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
